### ISSUE TITLE
Getting issue while building

### ISSUE THREAD

**Issue by vashukarn** [Sivaprasath12/Coherent_SoundGenerator#1]
Getting issue while building
![image](https://github.com/user-attachments/assets/0afb4577-b876-4e4f-99d8-3fe74b1b6c6a)

**Comment by jebaseelancoherent** [comment]
To better assist you, could you please provide the versions you're using for Gradle, Kotlin, and Flutter?

**Comment by jebaseelancoherent** [comment]
Hi Vashukarn, the build issue has been fixed.
